## Disease Prediction from Symptoms

For this project, we'll be using the dataset from here: http://people.dbmi.columbia.edu/~friedma/Projects/DiseaseSymptomKB/index.html

Copy the data from all the columns and paste it into an excel sheet -> `raw_data.xlsx`

In [1]:
# Import Dependencies
import csv
import pandas as pd
import numpy as np
from collections import defaultdict
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Read Raw Dataset
df = pd.read_csv('./dataset/raw_data.csv')

In [3]:
df.head()

Disease  Count of Disease Occurrence  \
0  UMLS:C0020538_hypertensive disease                       3363.0   
1                                 NaN                          NaN   
2                                 NaN                          NaN   
3                                 NaN                          NaN   
4                                 NaN                          NaN   

                             Symptom  
0           UMLS:C0008031_pain chest  
1  UMLS:C0392680_shortness of breath  
2            UMLS:C0012833_dizziness  
3             UMLS:C0004093_asthenia  
4                 UMLS:C0085639_fall

In [4]:
# Fill all NaN with the values above
data = df.fillna(method='ffill')

In [5]:
data.head()

Disease  Count of Disease Occurrence  \
0  UMLS:C0020538_hypertensive disease                       3363.0   
1  UMLS:C0020538_hypertensive disease                       3363.0   
2  UMLS:C0020538_hypertensive disease                       3363.0   
3  UMLS:C0020538_hypertensive disease                       3363.0   
4  UMLS:C0020538_hypertensive disease                       3363.0   

                             Symptom  
0           UMLS:C0008031_pain chest  
1  UMLS:C0392680_shortness of breath  
2            UMLS:C0012833_dizziness  
3             UMLS:C0004093_asthenia  
4                 UMLS:C0085639_fall

In [6]:
# Process Disease and Symptom Names
def process_data(data):
    data_list = []
    data_name = data.replace('^','_').split('_')
    n = 1
    for names in data_name:
        if (n % 2 == 0):
            data_list.append(names)
        n += 1
    return data_list

In [7]:
# Data Cleanup
disease_list = []
disease_symptom_dict = defaultdict(list)
disease_symptom_count = {}
count = 0

for idx, row in data.iterrows():
    
    # Get the Disease Names
    if (row['Disease'] !="\xc2\xa0") and (row['Disease'] != ""):
        disease = row['Disease']
        disease_list = process_data(data=disease)
        count = row['Count of Disease Occurrence']

    # Get the Symptoms Corresponding to Diseases
    if (row['Symptom'] !="\xc2\xa0") and (row['Symptom'] != ""):
        symptom = row['Symptom']
        symptom_list = process_data(data=symptom)
        for d in disease_list:
            for s in symptom_list:
                disease_symptom_dict[d].append(s)
            disease_symptom_count[d] = count

In [8]:
# See that the data is Processed Correctly
disease_symptom_dict

defaultdict(list,
            {'hypertensive disease': ['pain chest',
              'shortness of breath',
              'dizziness',
              'asthenia',
              'fall',
              'syncope',
              'vertigo',
              'sweat',
              'sweating increased',
              'palpitation',
              'nausea',
              'angina pectoris',
              'pressure chest'],
             'diabetes': ['polyuria',
              'polydypsia',
              'shortness of breath',
              'pain chest',
              'asthenia',
              'nausea',
              'orthopnea',
              'rale',
              'sweat',
              'sweating increased',
              'unresponsiveness',
              'mental status changes',
              'vertigo',
              'vomiting',
              'labored breathing'],
             'depression mental': ['feeling suicidal',
              'suicidal',
              'hallucinations auditory',
              'feel

In [9]:
# Count of Disease Occurence w.r.t each Disease
disease_symptom_count

{'hypertensive disease': 3363.0,
 'diabetes': 1421.0,
 'depression mental': 1337.0,
 'depressive disorder': 1337.0,
 'coronary arteriosclerosis': 1284.0,
 'coronary heart disease': 1284.0,
 'pneumonia': 1029.0,
 'failure heart congestive': 963.0,
 'accident\xa0cerebrovascular': 885.0,
 'asthma': 835.0,
 'myocardial infarction': 759.0,
 'hypercholesterolemia': 685.0,
 'infection': 630.0,
 'infection urinary tract': 597.0,
 'anemia': 544.0,
 'chronic obstructive airway disease': 524.0,
 'dementia': 504.0,
 'insufficiency renal': 445.0,
 'confusion': 408.0,
 'degenerative\xa0polyarthritis': 405.0,
 'hypothyroidism': 398.0,
 'anxiety state': 390.0,
 'malignant neoplasms': 354.0,
 'primary malignant neoplasm': 354.0,
 'acquired\xa0immuno-deficiency syndrome': 350.0,
 'HIV': 350.0,
 'hiv infections': 350.0,
 'cellulitis': 341.0,
 'gastroesophageal reflux disease': 325.0,
 'septicemia': 311.0,
 'systemic infection': 311.0,
 'sepsis (invertebrate)': 311.0,
 'deep vein thrombosis': 310.0,
 'deh

In [10]:
# Save cleaned data as CSV
f = open('./dataset/cleaned1_data.csv', 'w')

with f:
    writer = csv.writer(f)
    for key, val in disease_symptom_dict.items():
        for i in range(len(val)):
            writer.writerow([key, val[i], disease_symptom_count[key]])

In [12]:
# Read Cleaned Data as DF
df = pd.read_csv('./dataset/cleaned1_data.csv')
df.columns = ['disease', 'symptom', 'occurence_count']
df.head()


disease  \
0  hypertensive disease                    
1  hypertensive disease                    
2  hypertensive disease                    
3  hypertensive disease                    
4  hypertensive disease                    

                                       symptom  occurence_count  
0  shortness of breath                                   3363.0  
1  dizziness                                             3363.0  
2  asthenia                                              3363.0  
3  fall                                                  3363.0  
4  syncope                                               3363.0

In [14]:
# Remove any rows with empty values
df.replace(float('nan'), np.nan, inplace=True)
df.dropna(inplace=True)

In [15]:
from sklearn import preprocessing

In [16]:
n_unique = len(df['symptom'].unique())
n_unique

405

In [17]:
df.dtypes

disease             object
symptom             object
occurence_count    float64
dtype: object

In [18]:
# Encode the Labels
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(df['symptom'])
print(integer_encoded)

[329  88  29 ... 131 123 123]


In [19]:
# One Hot Encode the Labels
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
onehot_encoded[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [21]:
len(onehot_encoded[0])

405

In [22]:
cols = np.asarray(df['symptom'].unique())
cols

array(['shortness of breath                        ',
       'dizziness                                  ',
       'asthenia                                   ',
       'fall                                       ',
       'syncope                                    ',
       'vertigo                                    ',
       'sweat                                      ',
       'sweating increased                         ',
       'palpitation                                ',
       'nausea                                     ',
       'angina pectoris                            ',
       'pressure chest                             ',
       'polyuria                                   ',
       'polydypsia                                 ',
       'pain chest                                 ',
       'orthopnea                                  ',
       'rale                                       ',
       'unresponsiveness                           ',
       'mental status change

In [23]:
# Create a new dataframe to save OHE labels
df_ohe = pd.DataFrame(columns = cols)
df_ohe.head()

Empty DataFrame
Columns: [shortness of breath                        , dizziness                                  , asthenia                                   , fall                                       , syncope                                    , vertigo                                    , sweat                                      , sweating increased                         , palpitation                                , nausea                                     , angina pectoris                            , pressure chest                             , polyuria                                   , polydypsia                                 , pain chest                                 , orthopnea                                  , rale                                       , unresponsiveness                           , mental status changes                      , vomiting                                   , labored breathing                          , feeling suicidal                           , suicidal                                   , hallucinations auditory                    , feeling hopeless                           , weepiness                                  , sleeplessness                              , motor retardation                          , irritable mood                             , blackout                                   , mood depressed                             , hallucinations visual                      , worry                                      , agitation                                  , tremor                                     , intoxication                               , verbal auditory hallucinations             , energy increased                           , difficulty                                 , nightmare                                  , unable to concentrate                      , homelessness                               , hypokinesia                                , dyspnea on exertion                        , chest tightness                            , cough                                      , fever                                      , decreased translucency                     , productive cough                           , pleuritic pain                             , yellow sputum                              , breath sounds decreased                    , chill                                      , rhonchus                                   , green sputum                               , non-productive cough                       , wheezing                                   , haemoptysis                                , distress respiratory                       , tachypnea                                  , malaise                                    , night sweat                                , jugular venous distention                  , dyspnea                                    , dysarthria                                 , speech slurred                             , facial paresis                             , hemiplegia                                 , seizure                                    , numbness                                   , symptom aggravating factors                , st segment elevation                       , st segment depression                      , t wave inverted                            , presence of q wave                         , chest discomfort                           , bradycardia                                , pain                                       , nonsmoker                                  , erythema                                   , hepatosplenomegaly                         , pruritus                                   , diarrhea                                   , abscess bacterial                          , swelling                                   , apyrexial                                  , dysuria                                    , hematuria                                  , renal angle te

In [24]:
for i in range(len(onehot_encoded)):
    df_ohe.loc[i] = onehot_encoded[i]

In [25]:
df_ohe.head()

shortness of breath                          \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   dizziness                                    \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   asthenia                                     \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   fall                                         \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   syncope                                      \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   vertigo                                      \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   sweat                                        \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   sweating increased                           \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   palpitation                                  \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   nausea                                       ...  \
0                                          0.0  ...   
1                                          0.0  ...   
2                                          0.0  ...   
3                                          0.0  ...   
4                                          0.0  ...   

   feces in rectum                              \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   prodrome                                     \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   hypoproteinemia                              \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   alcohol binge episode                        \
0         

In [26]:
len(df_ohe)

2130

In [27]:
# Disease Dataframe
df_disease = df['disease']
df_disease.head()

0    hypertensive disease                 
1    hypertensive disease                 
2    hypertensive disease                 
3    hypertensive disease                 
4    hypertensive disease                 
Name: disease, dtype: object

In [28]:
# Concatenate OHE Labels with the Disease Column
df_concat = pd.concat([df_disease,df_ohe], axis=1)
df_concat.head()

disease  \
0  hypertensive disease                    
1  hypertensive disease                    
2  hypertensive disease                    
3  hypertensive disease                    
4  hypertensive disease                    

   shortness of breath                          \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   dizziness                                    \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   asthenia                                     \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   fall                                         \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   syncope                                      \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   vertigo                                      \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   sweat                                        \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   sweating increased                           \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   palpitation                                  ...  \
0                                          0.0  ...   
1                                          0.0  ...   
2                                          0.0  ...   
3                                          0.0  ...   
4                                          0.0  ...   

   feces in rectum                              \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   prodrome                                     \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   hypoproteinemia                              \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   alcohol binge episode                        \
0                                          0.0   
1                         

In [29]:
df_concat.drop_duplicates(keep='first',inplace=True)

In [30]:
df_concat.head()

disease  \
0  hypertensive disease                    
1  hypertensive disease                    
2  hypertensive disease                    
3  hypertensive disease                    
4  hypertensive disease                    

   shortness of breath                          \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   dizziness                                    \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   asthenia                                     \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   fall                                         \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   syncope                                      \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   vertigo                                      \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   sweat                                        \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   sweating increased                           \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   palpitation                                  ...  \
0                                          0.0  ...   
1                                          0.0  ...   
2                                          0.0  ...   
3                                          0.0  ...   
4                                          0.0  ...   

   feces in rectum                              \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   prodrome                                     \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   hypoproteinemia                              \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   alcohol binge episode                        \
0                                          0.0   
1                         

In [31]:
len(df_concat)

2115

In [32]:
cols = df_concat.columns
cols

Index(['disease', 'shortness of breath                        ',
       'dizziness                                  ',
       'asthenia                                   ',
       'fall                                       ',
       'syncope                                    ',
       'vertigo                                    ',
       'sweat                                      ',
       'sweating increased                         ',
       'palpitation                                ',
       ...
       'feces in rectum                            ',
       'prodrome                                   ',
       'hypoproteinemia                            ',
       'alcohol binge episode                      ',
       'abdomen acute                              ',
       'air fluid level                            ',
       'catching breath                            ',
       'large-for-dates fetus                      ',
       'immobile                                   ',
      

In [33]:
cols = cols[1:]

In [34]:
# Since, every disease has multiple symptoms, combine all symptoms per disease per row
df_concat = df_concat.groupby('disease').sum()
df_concat = df_concat.reset_index()
df_concat[:5]

disease  \
0  Alzheimer's disease                     
1  HIV                                     
2  Pneumocystis�carinii�pneumonia          
3  accident�cerebrovascular                
4  acquired�immuno-deficiency syndrome     

   shortness of breath                          \
0                                          0.0   
1                                          1.0   
2                                          0.0   
3                                          0.0   
4                                          1.0   

   dizziness                                    \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   asthenia                                     \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   fall                                         \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   syncope                                      \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   vertigo                                      \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   sweat                                        \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   sweating increased                           \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   palpitation                                  ...  \
0                                          0.0  ...   
1                                          0.0  ...   
2                                          0.0  ...   
3                                          0.0  ...   
4                                          0.0  ...   

   feces in rectum                              \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   prodrome                                     \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   hypoproteinemia                              \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   alcohol binge episode                        \
0                                          0.0   
1                         

In [35]:
len(df_concat)

149

In [36]:
df_concat.to_csv("./dataset/training_dataset.csv", index=False)

In [37]:
# One Hot Encoded Features
X = df_concat[cols]

# Labels
y = df_concat['disease']

## Model Training

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, export_graphviz

In [46]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [47]:
len(X_train), len(y_train)

(119, 119)

In [48]:
len(X_test), len(y_test)

(30, 30)

In [49]:
dt = DecisionTreeClassifier()
clf_dt=dt.fit(X, y)

In [50]:
clf_dt.score(X, y)

0.8993288590604027

In [51]:
export_graphviz(dt, 
                out_file='./tree.dot', 
                feature_names=cols)

In [52]:
!pip install graphviz

In [53]:
from graphviz import Source
from sklearn import tree

graph = Source(export_graphviz(dt,  out_file=None,  feature_names=cols))

png_bytes = graph.pipe(format='png')

with open('tree.png','wb') as f:
    f.write(png_bytes)

In [54]:
from IPython.display import Image
Image(png_bytes)

In [55]:
disease_pred = clf_dt.predict(X)

In [56]:
disease_real = y.values

In [57]:
for i in range(0, len(disease_real)):
    if disease_pred[i]!=disease_real[i]:
        print ('Pred: {0}\nActual: {1}\n'.format(disease_pred[i], disease_real[i]))

Pred: HIV                                  
Actual: acquired�immuno-deficiency syndrome  

Pred: biliary calculus                     
Actual: cholelithiasis                       

Pred: coronary arteriosclerosis            
Actual: coronary heart disease               

Pred: depression mental                    
Actual: depressive disorder                  

Pred: HIV                                  
Actual: hiv infections                       

Pred: carcinoma breast                     
Actual: malignant neoplasm of breast         

Pred: carcinoma of lung                    
Actual: malignant neoplasm of lung           

Pred: carcinoma prostate                   
Actual: malignant neoplasm of prostate       

Pred: carcinoma colon                      
Actual: malignant tumor of colon             

Pred: candidiasis                          
Actual: oral�candidiasis                     

Pred: effusion pericardial                 
Actual: pericardial effusion body substance  


In [63]:
from sklearn.metrics import accuracy_score
print(accuracy_score(disease_real,disease_pred))

0.8993288590604027
